#!/usr/bin/env python3
"""Regenerate icons.js from ../assets/icons/*.svg.

The prototypes open from disk. An external SVG referenced as a CSS mask or as <use href="file.svg#id">
does not load over file://, so the icons have to live inside the document — this script turns the
asset files into one sprite that any prototype can include with a single <script>.

Run it after adding an icon to ../assets/icons/:

    python3 knowledge/design-system/prototype-kit/build-icons.py

Nothing here invents an icon. Every file in ../assets/icons/ is an export from the Golem Figma
libraries with two mechanical edits, recorded in ../assets/README.md: the #E5E5E5 swatch rectangle
Figma adds around a component is removed, and the black fill becomes currentColor.
"""
import pathlib
import re

KIT = pathlib.Path(__file__).parent
ICONS = KIT.parent / "assets" / "icons"
OUT = KIT / "icons.js"

HEADER = """/* Golem icons as an inline sprite — generated by build-icons.py, do not edit by hand.

   Usage in a prototype:
     <script src="<path>/knowledge/design-system/prototype-kit/icons.js"></script>
     <svg class="icon" aria-hidden="true"><use href="#es-wallet"></use></svg>

   Every icon is an export from '💠 ES Icon' or '💠 ES Essentials'; the file name is the Figma
   component name in kebab-case. Sizes: ES Icon is 24 x 24, the carets are 8 x 16, close is 16 x 16.
   The sprite is injected as soon as the script runs, so it works before DOMContentLoaded. */
(function () {
  var ICONS = {
"""

FOOTER = """  };

  var ns = 'http://www.w3.org/2000/svg';
  var sprite = document.createElementNS(ns, 'svg');
  sprite.setAttribute('width', '0');
  sprite.setAttribute('height', '0');
  sprite.setAttribute('aria-hidden', 'true');
  sprite.setAttribute('focusable', 'false');
  sprite.style.position = 'absolute';
  var markup = '';
  Object.keys(ICONS).forEach(function (name) {
    markup += '<symbol id="es-' + name + '" viewBox="' + ICONS[name].viewBox + '">'
            + ICONS[name].body + '</symbol>';
  });
  sprite.innerHTML = markup;
  (document.body || document.documentElement).appendChild(sprite);

  /* The sizes the design system draws each icon at, so a prototype never has to guess. */
  window.GolemIcons = ICONS;
})();
"""


def main() -> None:
    entries = []
    for path in sorted(ICONS.glob("*.svg")):
        svg = path.read_text()
        view_box = re.search(r'viewBox="([^"]+)"', svg).group(1)
        body = svg.split(">", 1)[1].rsplit("</svg>", 1)[0]
        body = " ".join(body.split())
        body = body.replace("\\", "\\\\").replace("'", "\\'")
        entries.append(
            "    '%s': { viewBox: '%s', body: '%s' }" % (path.stem, view_box, body)
        )
    OUT.write_text(HEADER + ",\n".join(entries) + "\n" + FOOTER)
    print(f"{OUT.name}: {len(entries)} icons, {OUT.stat().st_size} bytes")


if __name__ == "__main__":
    main()
